### ISSUE TITLE
v4.0

### ISSUE THREAD

**Issue by rubiii** [savonrb/wasabi#27]
There's a lot of stuff I want to hack on for 4.0, so here's my TODO list:
- [x] Solve performance problems [#7](https://github.com/savonrb/wasabi/issues/7).
- [x] Support WSDL imports [#1](https://github.com/savonrb/wasabi/issues/1).
- [x] Properly separate operations by service and port.
- [x] Support XML Schema imports.
- [x] Remove the dependency on HTTPI as an HTTP client.
- [x] Parse operation input parameters and generate a map of types for the message body.
- [x] Integrate Wasabi 4.0 with Savon so people can easily test it as soon as possible.
- [x] Add support for message headers defined in the WSDL.
- [x] Finish initial documentation.
- [x] Push to GitHub!
- [x] Add support for attributes.
- [ ] Change the response Hash format to match the request Hash format.
- [ ] Convert Hash values to SOAP values (DateTime, etc) according to the type definition.
- [ ] Support WS-Policy/WS-Addressable (see savonrb/savon#409).
- [ ] Store the proper order of parameters so we can get rid of the `:order!` hack.
- [ ] Support for multipart responses using the new Savon::Multipart gem.
- [ ] Maybe support relative WSDL/Schema import locations? Can't find the specification for this.

This list is far from complete and constantly updated. If you feel like anythings missing, please let me know.
Major changes are also added to the [CHANGELOG](https://github.com/savonrb/wasabi/blob/master/CHANGELOG.md) and the [README](https://github.com/savonrb/wasabi/blob/master/README.md) should reflect the interface changes.
