### ISSUE TITLE
v3.2.0

### ISSUE THREAD

**Issue by rubiii** [savonrb/wasabi#28]
List of changes for the upcoming v3.2.0 release.
- [x] #7 Major speed improvements.
- [x] #25 Fixes a problem where Wasabi escaped an already escaped endpoint URL.
- [x] #20 Limited support for listing an operation's parameters.  
  Please note that if your WSDL defines imports, this method might not return all types.
- [x] #15 Fixes a bug where the operation tag name was not correctly extracted from the WSDL document.
- [x] #16 Various improvements regarding element order and type information.
